### ISSUE TITLE
KLocalizations.of(context); is null

### ISSUE THREAD

**Issue by zaid13** [nombrekeff/klocalizations_flutter#8]
this is how my code is structered but im getting null when i call KLocalizations.of(context);

`const supportedLocales = [
  Locale('en', 'GB'),
  Locale('de', 'DE'),
];

void main() {
  runApp(
    KLocalizations.asChangeNotifier(
      locale: supportedLocales[0],
      defaultLocale: supportedLocales[0],
      supportedLocales: supportedLocales,
      child: Phoenix(child: const MainApp()),
    ),
  );
}

GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

class MainApp extends StatefulWidget {
  const MainApp({Key? key}) : super(key: key);

  @override
  _MainAppState createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  LocaleProvider provider = LocaleProvider();

  bool _isOldUserShowed = false;
  @override
  void initState() {
    _initLanguage();

    provider.addListener(() {
      setState(() {});
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    final klocalizations = KLocalizations.of(context);
    print(klocalizations);`

**Comment by nombrekeff** [comment]
Hey there @zaid13! Thanks for filing the issue, from looking at your code it seems correct. The only thing that might be causing the issue is the Phoenix package, can you try without Phoenix and let me know if that works? If it's a phoenix thing I will try to replicate it locally and look for a fix.

A couple of questions that might help me figure this one out:
* What version of the package are you using? 
* Can you provide the output of `flutter doctor`?
* Are the translation files created for the defined locales?

**Comment by zaid13** [comment]
@nombrekeff  thanks for responding 

  klocalizations_flutter: ^0.0.8

[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19043.1889], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.3)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[√] Android Studio (version 4.2)
[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
[√] VS Code (version 1.62.3)
[√] Connected device (3 available)

yes the translation files are set up locally in assets/translation

**Comment by zaid13** [comment]
i have removed the 
pheonix now and my code look like this 


`void main() {
  runApp(
    KLocalizations.asChangeNotifier(
      locale: supportedLocales[0],
      defaultLocale: supportedLocales[0],
      supportedLocales: supportedLocales,
      child: const MainApp(),
    ),
  );
}
`

**Comment by nombrekeff** [comment]
Cheers @zaid13, thanks for the info. It seems correct though, should work for flutter@2.10.5 (but have not tested myself, will try to replicate it between today and tomorrow). Does it still return null after removing phoenix? I'm guessing there's no error for this at runtime right?

One thing I noticed is that you have the translations in `/assets/translation` instead of `/assets/translations`, is this the case? If so, try renaming the folder to `translations`, or provide `localizationsAssetsPath` to .asChangeNotifier method pointing to the correct folder.  

It's a bit weird, but we will figure it out.

**Comment by zaid13** [comment]
Thanks alot 

 it still returns the same error on the runtime 

I have corrected the path but still same error

**Comment by nombrekeff** [comment]
Okay, I think I know what the reason is, can you try with v0.0.7? If that works I will make a quick update to revert a change I did a couple of weeks back. 

I'm very sorry for the inconvenience! Your report will help make the package better!

**Comment by zaid13** [comment]
Same error on 0.0.7

**Comment by nombrekeff** [comment]
Crap... would you mind sharing a basic example where the issue can be replicated? I will then check it out tonight and see if I can replicate the bug.

**Comment by zaid13** [comment]
klocalizations_flutter: ^0.0.6


Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.3, on macOS 11.5.2 20G95 darwin-arm, locale en-PK)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] Connected device (2 available)
[☠] HTTP Host Availability (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ HandshakeException: Connection terminated



```
import 'package:example/http_loader.dart';
import 'package:flutter/material.dart';
import 'package:klocalizations_flutter/klocalizations_flutter.dart';

// Define you locales somewhere
const supportedLocales = [
  Locale('en', 'GB'),
  Locale('es', 'ES'),
  Locale('ar', 'AR'),
  Locale('gr', 'GR'),
];

void main() {
  runApp(
    KLocalizations.asChangeNotifier(
      locale: supportedLocales[0],
      defaultLocale: supportedLocales[0],
      supportedLocales: supportedLocales,
      loader: HttpLoader(),
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final klocalizations = KLocalizations.of(context);

    return MaterialApp(
      title: 'Flutter Demo',
      locale: klocalizations?.locale,
      supportedLocales: klocalizations?.supportedLocales ?? [],
      localizationsDelegates: [
        klocalizations?.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate
      ],
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'home.title'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    var theme = Theme.of(context);
    var klocalizations = KLocalizations.of(context);

    return Scaffold(
      appBar: AppBar(
        title: LocalizedText(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            LocalizedText(
              'home.welcome',
              style: theme.textTheme.headline5,
            ),
            LanguageSelector(
              locale: klocalizations!.locale,
              supportedLocales: klocalizations.supportedLocales,
              onChange: (locale) {
                klocalizations
                    .setLocale(locale ?? klocalizations.defaultLocale);
              },
            ),
            LocalizedText.selectable(
              'home.counter',
              params: {
                'count': _counter,
              },
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

**Comment by zaid13** [comment]
i have cloned it from 
https://github.com/nombrekeff/klocalizations_flutter

but still same error

**Comment by nombrekeff** [comment]
Okay, I've checked the example provided in the package (latest version) and it works for version 2.10.5 and latest 3.3.0, so it should also work for any version in between. 

Do you get any error or warning in the console at buildtime or runtime?

**Comment by zaid13** [comment]
<img width="1469" alt="Screenshot 2022-09-12 at 4 21 24 PM" src="https://user-images.githubusercontent.com/47746351/189641152-136f6b51-daf1-46b2-8b12-272d637e25be.png">

**Comment by zaid13** [comment]
have you tested the example in the code ?

**Comment by zaid13** [comment]
also what was the library version ?

**Comment by zaid13** [comment]
<img width="1196" alt="Screenshot 2022-09-12 at 4 27 04 PM" src="https://user-images.githubusercontent.com/47746351/189642159-eeeab324-bf3d-448b-b581-d54a1800e45c.png">

**Comment by nombrekeff** [comment]
Yup, I tested with the latest version, with flutter 2.10.5 which is the one you use in the first example and 3.3.0 which is the latest.

**Comment by zaid13** [comment]
i have tested on 3.3.0 on different machines with different version but the error persists but then i used **easy_localization** package and it works fine 

anything that im missing over here ?

**Comment by zaid13** [comment]
instead of :

   ` final klocalizations = KLocalizations.of(context);`

 i used :

`final klocalizations = Provider.of<KLocalizations>(context);`

and it works like a charm now

**Comment by nombrekeff** [comment]
Oh fantastic, supposedly v0.0.7 used provider.of instead of localizations.of. I will make an update tomorrow and add provider back. Thanks for figuring it out, I was really busy today!!!!

**Comment by didiabel** [comment]
hey @nombrekeff  im still getting this null bug!
